name: Deploy via FTPS to Reg.ru (AntonX.io)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Upload qua FTPS (port 21)
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftps
          port: 21
          local-dir: site/            # đổi về dist/ build/ hoặc out/ khi dùng build thật
          server-dir: /www/antonx.io/
          state-name: .ftp-deploy-sync-state.json
          dangerous-clean-slate: true
          exclude: |
            **/.git*
            /.github/
