
name: Deploy via FTPS to Reg.ru (AntonX.io)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: FTP Deploy (FTPS port 21)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftps
          port: 21
          local-dir: site/            # sau này đổi thành dist/ hoặc out/
          server-dir: /www/antonx.io/
          state-name: .ftp-deploy-sync-state.json
          dangerous-clean-slate: true
          exclude: |
            **/.git*
            /.github/
